package audiana;

import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import audiana.config.ConfigManager;
import audiana.file.FileManager;

/** Contains the script for navigating through Audiana.
 * 
 * Written By Dillon Michael Jones
 * Project Started on Wed, Aug 26, 2026, 12:02 PM
 * Affiliated with Columbus State Univeristy - CPSC 2108 
 * 
 * Note to Janace Canedo: I have decided to turn this into a personal project once I complete and submit version 1, which will be 
 * simple enough to satisfy the objectives of the assignment. Feel free to provide feedback, as I plan to port this to a TUI 
 * layer using Lanterna. Thank You!
 * 
 */

public class Main {

    public static void main(String[] args) {
        
        ConfigManager.load();
        Logger.getLogger("org.jaudiotagger").setLevel(Level.OFF);

        String versionNumber = "v1.0.0"; // Current Version //
        boolean audianaIsRunning = true;

        // ASCII Art Generated by ChatGPT //
        String audianaLogo = """ 
            _              _ _
           / 1   _   _  __| (_) __ _ _ __   __ _
          / _ 1 | | | |/ _` | |/ _` | '_ 1 / _` |
         / ___ 1| |_| | (_| | | (_| | | | | (_| |
        /_/   1_11__,_|1__,_|_|1__,_|_| |_|1__,_| """.replace("1", "\\"); 

        System.out.println("\n" + audianaLogo + " " + versionNumber);

        Scanner scanner = new Scanner(System.in);

        do {

            System.out.print("\n" +  "D - Directory Setup, F - File Selection,  E - Exit: ");
            String menuSelection = scanner.nextLine();
            switch(menuSelection.toUpperCase()) {
                case "D" -> // D - Directory Setup //
                    FileManager.setupDirectory(scanner);
        
                case "F" -> // F - File Selection //
                    FileManager.browseFiles(scanner);
                
                case "E" -> {
                    ConfigManager.save();
                    audianaIsRunning = false;
                    // Exit - Will Terminate Application //
                }
                default -> System.out.print("ERROR: Invalid Selection! ");
                // Any Other Input //
            }

        } while (audianaIsRunning);

    }
}


