package audiana;
import java.io.File;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jaudiotagger.audio.AudioFileIO;

/**
 * Contains the navigation from the File Selection Menu to the Analysis Menu (and later the Playback Menu).
 * 
 * NOTE TO PROFFESSOR: I have decided to turn this into a personal project once I complete and submit version 1, which will be 
 * simple enough to satisfy the objectives of the assignment. Feel free to provide feedback, as I plan to port this to a TUI 
 * layer using Lanterna.
 * 
 */

public class Main {

    public static String SetupDirectory(Scanner scan) { 

        Boolean pathIsValid;
        String directory;
        File folder;

        do { 
            System.out.print("Enter your Music Folder Path: ");
            directory = scan.nextLine();
            folder = new File(directory);
            
            if(!folder.isDirectory()) {
                System.out.println("ERROR: Not a valid directory. ");
                pathIsValid = false;
            }
            else { 
                
                pathIsValid = true; 
            }
        } while (!pathIsValid);
        return directory;

    }

    public static Playlist createPlaylist(String directory) {
        int size = 0;
        File directoryFolder = new File(directory);
        File[] folderContents = directoryFolder.listFiles();

        if(directory == "" || directory == null ) { return null; }

        if (folderContents == null || folderContents.length == 0) {
            System.out.println("ERROR: No Files Found.");
            return null;
        }
        AudioTrack[] trackArray = new AudioTrack[folderContents.length];
                
        for (int i = 0; i < folderContents.length; i++) {
            if(folderContents[i].isFile()) {
                try {
                    trackArray[size] = new AudioTrack(AudioFileIO.read(folderContents[i]));
                    size++;
                }       
                catch (Exception e) {
                    System.out.println("WARNING: " + e);
                }
            }
            else if(folderContents[i].isDirectory()){
                System.out.println("WARNING: Cannot read Subfolders: ");
            }
        }
        return new Playlist(trackArray,size);
    }

    public static void DisplayPlaylist(Playlist playlist, Scanner scan) {
        System.out.println("\n" + " Playlist " + "\n" + "-------------");
                    
        int numSelect = 0;
        String input;
        if(playlist == null) { 
            System.out.println("\n" + "NO FILES FOUND" ); 
        }
        else {
            for (numSelect = 0; numSelect < playlist.size; numSelect++) {
                System.out.println((numSelect + 1) + ": " + playlist.files[ numSelect].name);
            }
            do {
                System.out.print("\n" + "( 1 - " + (playlist.size) + " ) Select : " ); 
                input = scan.nextLine();
                        
                try {
                    numSelect = Integer.parseInt(input);
                }       
                catch (NumberFormatException e) {
                    System.out.println("ERROR: Selection must be the number associated with a file: ");
                    numSelect = 0;
                }
            } while(numSelect < 1 || numSelect > playlist.size);
            do {
                System.out.print("Selected File: " + playlist.files[numSelect].name + "\n" + "Q - Playback Mode, Z - Analysis Mode: "); // 
                input = scan.nextLine();
                if("Q".equals(input.toUpperCase())) {
                    System.out.print("Playback not implemented yet!");
                }
                else if ("Z".equals(input.toUpperCase())) {
                    System.out.print("\n" + numSelect + ": ");
                    playlist.files[numSelect-1].DisplayInfo();
                }
                else { 
                    System.out.println("ERROR: Selection must either be Q or Z: " + input); 
                }
            } while (!"Q".equals(input) && !"Z".equals(input));
        }
        
    }

    public static void main(String[] args) {
        
        String musicFolderPath = "";
        Logger.getLogger("org.jaudiotagger").setLevel(Level.OFF);
        String versionNumber = "v0.7.0"; // Current Version 
        Scanner scanner = new Scanner(System.in);
        Playlist playlist = null;

        // ASCII Art Generated by ChatGPT //
        String audianaLogo = """ 
            _              _ _
           / §   _   _  __| (_) __ _ _ __   __ _
          / _ § | | | |/ _` | |/ _` | '_ § / _` |
         / ___ §| |_| | (_| | | (_| | | | | (_| |
        /_/   §_§§__,_|§__,_|_|§__,_|_| |_|§__,_| """.replace("§", "\\"); 

        System.out.println("\n" + audianaLogo + " " + versionNumber);

        do {
            System.out.print("\n" +  "D - Directory Setup, G - Playlist View,  E - Exit: ");
            String menuSelection = scanner.nextLine();
            switch(menuSelection.toUpperCase()) {
            
                case "D": musicFolderPath = SetupDirectory(scanner); break;// D - Directory Setup
        
                case "G": playlist = createPlaylist(musicFolderPath); // G - Playlist View
                DisplayPlaylist(playlist, scanner); break; 
                    
                case "E": System.exit(0); // Exit - Will Terminate Application

                default: System.out.print("ERROR: Invalid Selection: "); break; // Any Other Input
            }
        }while (true);
    }
}

// Tools for me (hehe) //
//cd /Windows/CrossSystem/Software\ Developement/Audiana/
//mvn clean compile 
//mvn exec:java -Dexec.mainClass="audiana.Main"

