package audiana;
import java.io.File;
import java.util.Scanner;

import org.jaudiotagger.audio.AudioFile;
import org.jaudiotagger.audio.AudioFileIO;

/**
 * Contains the navigation from the File Selection Menu to the Analysis Menu (and later the Playback Menu).
 * 
 * NOTE TO PROFFESSOR: I have decided to turn this into a personal project once I complete and submit version 1, which will be 
 * simple enough to satisfy the objectives of the assignment. Feel free to provide feedback, as I plan to port this to a TUI 
 * layer using Lanterna.
 * 
 */

public class Main {
    public static void main(String[] args) {

        String versionNumber = "v0.1.0"; // <--- Current Version 

        String audianaLogo = """ 
            _              _ _
           / §   _   _  __| (_) __ _ _ __   __ _
          / _ § | | | |/ _` | |/ _` | '_ § / _` |
         / ___ §| |_| | (_| | | (_| | | | | (_| |
        /_/   §_§§__,_|§__,_|_|§__,_|_| |_|§__,_| """.replace("§", "\\"); // <--- ASCII Art Generated by ChatGPT

        System.out.println(audianaLogo + " " + versionNumber + "\n");
        Scanner scanner = new Scanner(System.in);
        Boolean pathIsValid;
        File file;
        
        // Input Loop - Asks for file path until it finds specified File // 
        do { 
            System.out.print("Enter The File Path (mp3, mp4, WAV, FLAC, Ogg): ");
            String path = scanner.nextLine();
            file = new File(path);

            System.out.println("Loading file " + path + "...");

            if(file.exists() && file.isFile()) {
                try {
                    AudioFile audioFile = AudioFileIO.read(file);
                    System.out.println("Audio file loaded!");
                    pathIsValid = true;
                    System.out.println(audioFile.getExt());
                }       
                catch (Exception e) {
                    System.out.println("ERROR: Unable to read audio file.");
                    pathIsValid = false;
                }
            }
            else { 
                System.out.println("ERROR: Not a file or doesnt exist. "); 
                pathIsValid = false;
            }
        } while (!pathIsValid);
    }
}

// Tools for me (hehe) //
//java -cp target/classes audiana.Main
//mvn exec:java -Dexec.mainClass="audiana.Main"

